!function(e){var n={};function r(t){if(n[t])return n[t].exports;var o=n[t]={i:t,l:!1,exports:{}};return e[t].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=n,r.d=function(e,n,t){r.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:t})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,n){if(1&n&&(e=r(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(r.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var o in e)r.d(t,o,function(n){return e[n]}.bind(null,o));return t},r.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(n,"a",n),n},r.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},r.p="",r(r.s="./src/js/main.js")}({"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _modules_animscroll__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./modules/animscroll */ "./src/js/modules/animscroll.js");\n/* harmony import */ var _modules_slider__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./modules/slider */ "./src/js/modules/slider.js");\n/* harmony import */ var _modules_adaptive__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./modules/adaptive */ "./src/js/modules/adaptive.js");\n/* harmony import */ var _modules_preloader__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./modules/preloader */ "./src/js/modules/preloader.js");\n/* harmony import */ var _modules_forms__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ./modules/forms */ "./src/js/modules/forms.js");\n\n\n\n\n\nwindow.addEventListener(\'DOMContentLoaded\', function () {\n  Object(_modules_animscroll__WEBPACK_IMPORTED_MODULE_0__["default"])();\n  Object(_modules_slider__WEBPACK_IMPORTED_MODULE_1__["default"])();\n  Object(_modules_adaptive__WEBPACK_IMPORTED_MODULE_2__["default"])();\n  Object(_modules_preloader__WEBPACK_IMPORTED_MODULE_3__["default"])();\n  Object(_modules_forms__WEBPACK_IMPORTED_MODULE_4__["default"])();\n});\n\n//# sourceURL=webpack:///./src/js/main.js?')},"./src/js/modules/adaptive.js":
/*!************************************!*\
  !*** ./src/js/modules/adaptive.js ***!
  \************************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\nfunction adaptive() {\n  var headerMenu = document.querySelectorAll(".header__menu");\n  var burger = document.querySelector(".burger");\n  var headerMenuBurger = document.querySelector(".header-menu");\n\n  function adaptiveHeader() {\n    var headerColumn = document.querySelectorAll(".header__column");\n    var width = window.outerWidth;\n\n    if (width < 767) {\n      headerMenu.forEach(function (item) {\n        headerMenuBurger.append(item);\n      });\n    } else {\n      headerColumn.forEach(function (column) {\n        if (column.classList.contains(\'header__column_right\')) {\n          column.prepend(document.querySelectorAll(".header__menu")[1]);\n        } else {\n          if (column.classList.contains(\'header__column_left\')) {\n            column.append(document.querySelectorAll(".header__menu")[0]);\n          }\n        }\n      });\n    }\n  }\n\n  adaptiveHeader();\n  burger.addEventListener(\'click\', function () {\n    burger.classList.toggle("burger_active");\n    headerMenuBurger.classList.toggle("header-menu_active");\n  });\n}\n\n/* harmony default export */ __webpack_exports__["default"] = (adaptive);\n\n//# sourceURL=webpack:///./src/js/modules/adaptive.js?')},"./src/js/modules/animscroll.js":
/*!**************************************!*\
  !*** ./src/js/modules/animscroll.js ***!
  \**************************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nfunction animScroll() {\n  var animItems = document.querySelectorAll('._anim-items');\n\n  if (animItems.length > 0) {\n    var animOnScroll = function animOnScroll() {\n      for (var index = 0; index < animItems.length; index++) {\n        var animItem = animItems[index];\n        var animItemHeight = animItem.offsetHeight;\n        var animItemOffset = offset(animItem).top;\n        var animStart = 4;\n        var animItemPoint = window.innerHeight - animItemHeight / animStart;\n\n        if (animItemHeight > window.innerHeight) {\n          animItemPoint = window.innerHeight - window.innerHeight / animStart;\n        }\n\n        if (pageYOffset > animItemOffset - animItemPoint && pageYOffset < animItemOffset + animItemHeight) {\n          animItem.classList.add('_anim-active');\n        } else {\n          animItem.classList.remove('_anim-active');\n        }\n      }\n    };\n\n    var offset = function offset(el) {\n      var rect = el.getBoundingClientRect(),\n          scrollLeft = window.pageXOffset || document.documentElement.scrollLeft,\n          scrollTop = window.pageYOffset || document.documentElement.scrollTop;\n      return {\n        top: rect.top + scrollTop,\n        left: rect.left + scrollLeft\n      };\n    };\n\n    window.addEventListener('scroll', animOnScroll);\n    setTimeout(function () {\n      animOnScroll();\n    }, 400);\n  }\n}\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (animScroll);\n\n//# sourceURL=webpack:///./src/js/modules/animscroll.js?")},"./src/js/modules/forms.js":
/*!*********************************!*\
  !*** ./src/js/modules/forms.js ***!
  \*********************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nfunction postForms() {\n  var forms = document.querySelectorAll('.get-contact__form');\n  forms.forEach(function (item) {\n    postData(item);\n  });\n  var message = {\n    loading: \"Загрузка\",\n    success: \"Спасибо, скоро мы с Вами свяжемся\",\n    failure: \"Ошибка...\"\n  };\n\n  function postData(form) {\n    form.addEventListener('submit', function (e) {\n      e.preventDefault();\n      var statusMessage = document.createElement('div');\n      statusMessage.classList.add('status');\n      statusMessage.textContent = message.loading;\n      form.append(statusMessage);\n      var request = new XMLHttpRequest();\n      request.open('POST', 'server.php');\n      request.setRequestHeader('Content-type', 'application/json');\n      var formData = new FormData(form);\n      var object = {};\n      formData.forEach(function (value, key) {\n        object[key] = value;\n      });\n      var json = JSON.stringify(object);\n      request.send(json);\n      request.addEventListener('load', function () {\n        if (request.status === 200) {\n          console.log(request.response);\n          statusMessage.textContent = message.success;\n          form.reset();\n          setTimeout(function () {\n            statusMessage.remove();\n          }, 2000);\n        } else {\n          statusMessage.textContent = message.failure;\n        }\n      });\n    });\n  }\n}\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (postForms);\n\n//# sourceURL=webpack:///./src/js/modules/forms.js?")},"./src/js/modules/preloader.js":
/*!*************************************!*\
  !*** ./src/js/modules/preloader.js ***!
  \*************************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\nfunction preloader() {\n  window.onload = function () {\n    var preload = document.querySelector(".preloader");\n    setTimeout(function () {\n      if (!preload.classList.contains("done")) {\n        preload.classList.add("done");\n        document.body.style.overflow = "visible";\n      }\n    }, 1000);\n  };\n}\n\n/* harmony default export */ __webpack_exports__["default"] = (preloader);\n\n//# sourceURL=webpack:///./src/js/modules/preloader.js?')},"./src/js/modules/slider.js":
/*!**********************************!*\
  !*** ./src/js/modules/slider.js ***!
  \**********************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nfunction slider() {\n  $(document).ready(function () {\n    $('.slider-img__wrapper').slick({\n      slidesToShow: 1,\n      slidesToScroll: 1,\n      centerMode: true,\n      initialSlide: 1,\n      variableWidth: true,\n      asNavFor: '.slider-content__wrapper'\n    });\n  });\n  $(document).ready(function () {\n    $('.slider-content__wrapper').slick({\n      slidesToShow: 1,\n      slidesToScroll: 1,\n      initialSlide: 1,\n      arrows: false,\n      fade: true,\n      asNavFor: '.slider-img__wrapper'\n    });\n  });\n}\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (slider);\n\n//# sourceURL=webpack:///./src/js/modules/slider.js?")}});
//# sourceMappingURL=main.js.map
